# XGBoost

In [1]:
import xgboost as xgb
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets

C:\Users\AMIT\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [2]:
iris = datasets.load_iris()

X,y = iris.data,iris.target

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=123)

xg_cl = xgb.XGBClassifier(objective = 'binary:logistic', n_estimators =10,seed =123)

xg_cl.fit(X_train,y_train)

preds= xg_cl.predict(X_test)

accuracy = float(np.sum(preds== y_test))/y_test.shape[0]
print('accuracy',accuracy)

accuracy 1.0

# trees as base learners in scikit API

In [3]:
data=pd.read_csv(r'C:\Users\AMIT\Desktop\MSIT_ML_CLASS-master-6\MSIT_ML_CLASS-master\datasets\boston_housing.csv')

In [4]:
X = data.iloc[:,:-1]
y = data.iloc[:,-1]

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 123)

xg_reg = xgb.XGBRegressor(objective = 'reg:linear',n_estimators =10 ,seed =123)

xg_reg.fit(X_train,y_train)

preds = xg_reg.predict(X_test)

from sklearn.metrics import mean_squared_error
rmse= np.sqrt(mean_squared_error(y_test,preds))

print('RMSE:',rmse)

RMSE: 173308.24999

# Tuning the model

In [5]:
data = pd.read_csv(r'C:\Users\AMIT\Desktop\MSIT_ML_CLASS-master-6\MSIT_ML_CLASS-master\datasets\boston_housing.csv')

#X,y =data[data.columns.tolist()[:-1]], data[data.columns.tolist()[-1]]
X=data.iloc[:,:-1]
y=data.iloc[:,-1]

data_dmatrix = xgb.DMatrix(data=X,label=y)

untuned_params = {'objective':'reg:linear'}

tuned_cv_results_rmse = xgb.cv(dtrain=data_dmatrix,params= untuned_params,num_boost_round=200, metrics ='rmse',as_pandas=True, seed =123)

print(type(tuned_cv_results_rmse))

print(tuned_cv_results_rmse)

print(tuned_cv_results_rmse['test-rmse-mean'].tail(1))

<class 'pandas.core.frame.DataFrame'>
     train-rmse-mean  train-rmse-std  test-rmse-mean  test-rmse-std
0      345641.635417      439.554530   346934.750000    1103.965446
1      249364.255208       33.179280   251460.807292     715.742581
2      181442.458333      434.621280   185377.510417    1995.195568
3      134333.744792      805.081166   140770.640625    1720.934621
4      102236.072917     1129.216471   110887.408854     835.306948
5       80036.684896     1405.373735    93484.687500     723.510622
6       65256.212240     1459.247443    82739.684896     840.189511
7       55071.916667     1526.804418    76620.445313    1433.650494
8       47991.230469     1356.147558    73194.651042    2089.560370
9       43494.865886     1211.302226    71217.671875    2821.949321
10      40707.936198     1121.331499    70319.354167    3151.402716
11      38573.195313     1328.563672    69973.774740    3445.808363
12      36558.989583     1339.580748    69784.667969    3583.742507
13      35464.348958     1430.417936    69593.093750    3655.623960
14      34302.899740     1176.906548    69744.214844    3537.344191
15      32341.111328     1167.300604    69949.441406    3697.965135
16      30514.359375     1042.274812    70302.794271    3700.439739
17      29610.044271     1134.312067    70437.010417    3785.045361
18      28544.033203     1121.815705    70727.421875    3731.371211
19      28157.108724     1142.906198    70997.635417    3841.179136
20      26975.038412      649.515231    71315.838541    4026.084766
21      26322.941406      966.892741    71321.346354    3967.627209
22      25439.084635      792.146120    71424.799479    3940.312511
23      24608.860677      914.422400    71550.450521    3890.740344
24      23591.402344      866.825082    71524.559896    3921.160672
25      23013.177083      929.280634    71629.877604    3896.681753
26      22447.747396      644.702185    71690.497396    3795.028268
27      21688.287110      562.199933    71743.416667    3796.434699
28      20980.259766      597.872523    72007.901042    3662.719044
29      20603.903646      718.786794    72178.505208    3711.837354
..               ...             ...             ...            ...
170       471.538381       39.482764    75081.575521    4723.207275
171       457.322602       38.198033    75086.687500    4726.269107
172       447.365763       40.322129    75088.580729    4727.140275
173       440.509908       41.007615    75089.500000    4726.450112
174       434.799184       40.019738    75088.117188    4727.833746
175       425.634796       41.485722    75089.398438    4727.678589
176       416.495280       46.047474    75088.335937    4727.942158
177       408.126709       48.936137    75089.468750    4728.421103
178       396.030498       46.677993    75089.205729    4731.655819
179       384.402822       44.084619    75090.231771    4733.334715
180       375.821726       38.540507    75091.671875    4732.567097
181       367.981323       35.902793    75092.736979    4732.636100
182       362.094574       37.551802    75093.669271    4732.046035
183       352.448456       36.977879    75094.286458    4733.882791
184       344.297658       40.255927    75094.346354    4736.228147
185       335.938721       36.201544    75095.666667    4736.065697
186       327.548625       30.957042    75096.427083    4734.908332
187       319.237111       30.370156    75097.898438    4737.100812
188       314.763723       28.490938    75098.125000    4738.378466
189       308.465322       26.947679    75099.169271    4738.111601
190       300.368805       25.510113    75101.466146    4736.605307
191       291.219350       24.334497    75102.174479    4737.380440
192       282.243312       25.184353    75102.908855    4738.453131
193       276.183863       22.023817    75103.322916    4738.677178
194       265.621826       22.228312    75104.140625    4738.508199
195       258.528987       21.102166    75105.104166    4738.424113
196       248.211879       25.196047    75105.828125    4738.245937
197       245.339788       26.324708    75104.671875    4737.774931
198       239.111430       22.938293    75105.450521    4738.749356
199       235.291346       23.659694    75105.236979    4738.400375

[200 rows x 4 columns]
199    75105.236979
Name: test-rmse-mean, dtype: float64

In [6]:
X = data.iloc[:,:-1]  # or X = data[data.columns.tolist()[:-1]]
y=data.iloc[:,-1]  # or y = data[data.columns.tolist()[-1]]

data_dmatrix = xgb.DMatrix(data = X,label=y)

tuned_params = {'objective':'reg:linear','colsample_bytree': 1, 'learning_rate': 0.1, 'max_depth': 5}

tuned_cv_results_rmse = xgb.cv(dtrain = data_dmatrix, params = tuned_params, nfold =4, num_boost_round=200,metrics ='rmse',as_pandas=True,seed=123)

print("Tuned rmse:",tuned_cv_results_rmse['test-rmse-mean'].tail(1))

Tuned rmse: 199    71871.344726
Name: test-rmse-mean, dtype: float64

In [7]:
tuned_cv_results_rmse

     train-rmse-mean  train-rmse-std  test-rmse-mean  test-rmse-std
0      437585.562500     1515.885120   437713.117188    5293.183385
1      395956.453125     1390.436305   396482.734375    5068.038255
2      358522.765625     1294.783893   359140.156250    5083.890838
3      324831.656250     1202.600855   325856.492188    4950.348102
4      294452.148438     1167.663666   296032.351562    4914.165395
5      267097.750000     1065.601962   269185.101562    5032.079252
6      242560.109375     1046.363207   245407.449219    4925.419631
7      220437.390625      968.827601   223616.699219    5319.641879
8      200553.546875      938.173763   204328.312500    5285.678519
9      182688.250000      942.273801   187009.828125    5359.921746
10     166677.542969      933.391986   171715.867188    5452.239877
11     152307.609375      971.004405   157861.250000    5513.900706
12     139420.714844      970.346285   145724.773438    5819.053665
13     127949.476562     1008.323694   135094.529297    5960.617574
14     117704.703125     1069.447117   125693.376953    6175.549663
15     108553.832032     1110.605338   117537.359375    6246.873441
16     100421.298828     1178.431026   110436.189453    6290.147581
17      93193.294922     1193.101688   104080.882813    6452.814581
18      86731.515625     1259.909650    98733.460938    6285.347314
19      80950.849610     1211.107149    94160.679687    6258.837244
20      75849.085938     1225.615271    90223.601562    6142.570158
21      71353.488281     1214.716094    86874.916015    6251.225414
22      67432.348633     1239.045236    83939.167969    6342.550256
23      63960.071289     1281.492094    81416.037110    6261.211690
24      60851.328125     1230.759108    79435.878906    6458.619356
25      58163.142578     1250.598814    77745.388672    6370.631841
26      55695.041992     1171.689769    76224.619141    6308.193688
27      53611.470703     1201.576315    74999.197266    6254.451453
28      51796.701172     1205.878056    74015.382813    6309.390086
29      50168.720703     1217.602858    73172.157226    6395.081495
..               ...             ...             ...            ...
170     18251.301270     1185.465928    71792.828125    6046.438911
171     18082.818847     1185.726670    71814.918945    6062.292122
172     18008.914063     1210.141869    71811.038086    6081.034800
173     17909.619141     1204.103283    71841.926758    6095.161782
174     17769.916992     1224.097659    71859.776368    6113.746109
175     17670.039062     1230.451435    71877.769531    6120.389491
176     17587.485107     1247.619060    71874.267578    6137.209965
177     17522.447265     1267.681145    71882.191406    6132.716775
178     17415.335205     1252.776330    71904.416992    6139.179841
179     17322.694336     1232.705366    71934.307618    6104.214697
180     17215.957031     1212.538585    71913.054688    6105.897317
181     17105.753906     1172.844798    71921.238281    6100.208564
182     17052.862549     1207.262489    71902.074219    6081.822713
183     16950.804199     1148.825613    71878.302734    6099.307888
184     16892.930908     1155.883265    71903.903320    6092.289101
185     16792.962890     1188.455178    71888.691406    6074.815862
186     16690.200195     1236.993508    71879.633789    6060.038719
187     16565.993408     1225.256705    71851.837890    6051.905067
188     16466.527099     1178.659848    71858.390625    6068.737766
189     16364.241944     1219.312940    71855.585938    6048.157225
190     16277.261719     1223.546832    71863.196289    6059.092780
191     16209.684814     1227.441565    71857.226562    6046.817308
192     16146.145996     1210.601602    71866.406250    6053.930011
193     16022.093262     1234.959542    71868.989258    6025.871197
194     15932.878418     1240.130953    71864.152344    6020.028457
195     15822.636719     1250.380226    71865.326172    6020.112015
196     15703.546142     1228.572446    71863.502930    5992.986465
197     15583.987549     1254.269409    71849.226562    6000.889791
198     15521.236084     1280.433572    71864.706054    6006.726503
199     15424.571045     1277.938166    71871.344726    6007.105313

[200 rows x 4 columns]

# XGBoost Part-2

In [8]:
df=pd.read_csv(r'C:\Users\AMIT\Desktop\MSIT_ML_CLASS-master-6\MSIT_ML_CLASS-master\datasets\ames_unprocessed_data.csv')
df.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Neighborhood,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,...,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,Fireplaces,GarageArea,PavedDrive,SalePrice
0,60,RL,65.0,8450,CollgCr,1Fam,2Story,7,5,2003,...,1710,1,0,2,1,3,0,548,Y,208500
1,20,RL,80.0,9600,Veenker,1Fam,1Story,6,8,1976,...,1262,0,1,2,0,3,1,460,Y,181500
2,60,RL,68.0,11250,CollgCr,1Fam,2Story,7,5,2001,...,1786,1,0,2,1,3,1,608,Y,223500
3,70,RL,60.0,9550,Crawfor,1Fam,2Story,7,5,1915,...,1717,1,0,1,0,3,1,642,Y,140000
4,60,RL,84.0,14260,NoRidge,1Fam,2Story,8,5,2000,...,2198,1,0,2,1,4,1,836,Y,250000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 21 columns):
MSSubClass      1460 non-null int64
MSZoning        1460 non-null object
LotFrontage     1201 non-null float64
LotArea         1460 non-null int64
Neighborhood    1460 non-null object
BldgType        1460 non-null object
HouseStyle      1460 non-null object
OverallQual     1460 non-null int64
OverallCond     1460 non-null int64
YearBuilt       1460 non-null int64
Remodeled       1460 non-null int64
GrLivArea       1460 non-null int64
BsmtFullBath    1460 non-null int64
BsmtHalfBath    1460 non-null int64
FullBath        1460 non-null int64
HalfBath        1460 non-null int64
BedroomAbvGr    1460 non-null int64
Fireplaces      1460 non-null int64
GarageArea      1460 non-null int64
PavedDrive      1460 non-null object
SalePrice       1460 non-null int64
dtypes: float64(1), int64(15), object(5)
memory usage: 211.1+ KB

In [10]:
# import labelencoder
from sklearn.preprocessing import LabelEncoder

df.LotFrontage = df.LotFrontage.fillna(0)
print(sum(df['LotFrontage'].isnull()))

0

In [11]:
# Create a boolean mask for categorical columns
categorical_mask = (df.dtypes =='object')
print(df.dtypes)
print(categorical_mask)

MSSubClass        int64
MSZoning         object
LotFrontage     float64
LotArea           int64
Neighborhood     object
BldgType         object
HouseStyle       object
OverallQual       int64
OverallCond       int64
YearBuilt         int64
Remodeled         int64
GrLivArea         int64
BsmtFullBath      int64
BsmtHalfBath      int64
FullBath          int64
HalfBath          int64
BedroomAbvGr      int64
Fireplaces        int64
GarageArea        int64
PavedDrive       object
SalePrice         int64
dtype: object
MSSubClass      False
MSZoning         True
LotFrontage     False
LotArea         False
Neighborhood     True
BldgType         True
HouseStyle       True
OverallQual     False
OverallCond     False
YearBuilt       False
Remodeled       False
GrLivArea       False
BsmtFullBath    False
BsmtHalfBath    False
FullBath        False
HalfBath        False
BedroomAbvGr    False
Fireplaces      False
GarageArea      False
PavedDrive       True
SalePrice       False
dtype: bool

In [12]:
categorical_columns = df.columns[categorical_mask].tolist()

In [13]:
df.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Neighborhood,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,...,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,Fireplaces,GarageArea,PavedDrive,SalePrice
0,60,RL,65.0,8450,CollgCr,1Fam,2Story,7,5,2003,...,1710,1,0,2,1,3,0,548,Y,208500
1,20,RL,80.0,9600,Veenker,1Fam,1Story,6,8,1976,...,1262,0,1,2,0,3,1,460,Y,181500
2,60,RL,68.0,11250,CollgCr,1Fam,2Story,7,5,2001,...,1786,1,0,2,1,3,1,608,Y,223500
3,70,RL,60.0,9550,Crawfor,1Fam,2Story,7,5,1915,...,1717,1,0,1,0,3,1,642,Y,140000
4,60,RL,84.0,14260,NoRidge,1Fam,2Story,8,5,2000,...,2198,1,0,2,1,4,1,836,Y,250000

In [14]:
print(categorical_columns)

# categorical  columns contain object type data

['MSZoning', 'Neighborhood', 'BldgType', 'HouseStyle', 'PavedDrive']

In [15]:
print(df[categorical_columns].head())

  MSZoning Neighborhood BldgType HouseStyle PavedDrive
0       RL      CollgCr     1Fam     2Story          Y
1       RL      Veenker     1Fam     1Story          Y
2       RL      CollgCr     1Fam     2Story          Y
3       RL      Crawfor     1Fam     2Story          Y
4       RL      NoRidge     1Fam     2Story          Y

In [16]:
# Create Labelencoder object: le
le = LabelEncoder()

df[categorical_columns]=df[categorical_columns].apply(lambda x: le.fit_transform(x))

print(df[categorical_columns].head())

   MSZoning  Neighborhood  BldgType  HouseStyle  PavedDrive
0         3             5         0           5           2
1         3            24         0           2           2
2         3             5         0           5           2
3         3             6         0           5           2
4         3            15         0           5           2

In [17]:
categorical_mask

MSSubClass      False
MSZoning         True
LotFrontage     False
LotArea         False
Neighborhood     True
BldgType         True
HouseStyle       True
OverallQual     False
OverallCond     False
YearBuilt       False
Remodeled       False
GrLivArea       False
BsmtFullBath    False
BsmtHalfBath    False
FullBath        False
HalfBath        False
BedroomAbvGr    False
Fireplaces      False
GarageArea      False
PavedDrive       True
SalePrice       False
dtype: bool

In [18]:
# import OneHotEncoder
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(categorical_features = categorical_mask, sparse=False)

df_encoded= ohe.fit_transform(df)

print(pd.DataFrame(df_encoded))


print(df.shape)

print(df_encoded.shape)

       0    1    2    3    4    5    6    7    8    9     ...      52      53  \
0     0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     0.0  1710.0
1     0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     0.0  1262.0
2     0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     1.0  1786.0
3     0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     1.0  1717.0
4     0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     0.0  2198.0
5     0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     1.0  1362.0
6     0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     1.0  1694.0
7     0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     0.0  2090.0
8     0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0    ...     1.0  1774.0
9     0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0    ...     1.0  1077.0
10    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     0.0  1040.0
11    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     1.0  2324.0
12    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     0.0   912.0
13    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     1.0  1494.0
14    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     0.0  1253.0
15    0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0    ...     1.0   854.0
16    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     0.0  1004.0
17    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     0.0  1296.0
18    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     0.0  1114.0
19    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     1.0  1339.0
20    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     1.0  2376.0
21    0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0    ...     1.0  1108.0
22    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     0.0  1795.0
23    0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0    ...     0.0  1060.0
24    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     1.0  1060.0
25    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     0.0  1600.0
26    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     1.0   900.0
27    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     1.0  1704.0
28    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     1.0  1600.0
29    0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0    ...     1.0   520.0
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...     ...     ...
1430  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     0.0  1838.0
1431  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     0.0   958.0
1432  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     1.0   968.0
1433  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     0.0  1792.0
1434  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     0.0  1126.0
1435  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     1.0  1537.0
1436  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     0.0   864.0
1437  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     0.0  1932.0
1438  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0    ...     1.0  1236.0
1439  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     0.0  1725.0
1440  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     1.0  2555.0
1441  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0    ...     0.0   848.0
1442  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     0.0  2007.0
1443  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0    ...     1.0   952.0
1444  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     0.0  1422.0
1445  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     0.0   913.0
1446  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     0.0  1188.0
1447  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     1.0  2090.0
1448  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     1.0  1346.0
1449  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0    ...     0.0   630.0
1450  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     0.0  1792.0
1451  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     1.0  1578.0
1452  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0    ...     0.0  1072.0
1453  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     0.0  1140.0
1454  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     1.0  1221.0
1455  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     1.0  1647.0
1456  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     1.0  2073.0
1457  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     1.0  2340.0
1458  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     1.0  1078.0
1459  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...     0.0  1256.0

       54   55   56   57   58   59     60        61
0     1.0  0.0  2.0  1.0  3.0  0.0  548.0  208500.0
1     0.0  1.0  2.0  0.0  3.0  1.0  460.0  181500.0
2     1.0  0.0  2.0  1.0  3.0  1.0  608.0  223500.0
3     1.0  0.0  1.0  0.0  3.0  1.0  642.0  140000.0
4     1.0  0.0  2.0  1.0  4.0  1.0  836.0  250000.0
5     1.0  0.0  1.0  1.0  1.0  0.0  480.0  143000.0
6     1.0  0.0  2.0  0.0  3.0  1.0  636.0  307000.0
7     1.0  0.0  2.0  1.0  3.0  2.0  484.0  200000.0
8     0.0  0.0  2.0  0.0  2.0  2.0  468.0  129900.0
9     1.0  0.0  1.0  0.0  2.0  2.0  205.0  118000.0
10    1.0  0.0  1.0  0.0  3.0  0.0  384.0  129500.0
11    1.0  0.0  3.0  0.0  4.0  2.0  736.0  345000.0
12    1.0  0.0  1.0  0.0  2.0  0.0  352.0  144000.0
13    0.0  0.0  2.0  0.0  3.0  1.0  840.0  279500.0
14    1.0  0.0  1.0  1.0  2.0  1.0  352.0  157000.0
15    0.0  0.0  1.0  0.0  2.0  0.0  576.0  132000.0
16    1.0  0.0  1.0  0.0  2.0  1.0  480.0  149000.0
17    0.0  0.0  2.0  0.0  2.0  0.0  516.0   90000.0
18    1.0  0.0  1.0  1.0  3.0  0.0  576.0  159000.0
19    0.0  0.0  1.0  0.0  3.0  0.0  294.0  139000.0
20    0.0  0.0  3.0  1.0  4.0  1.0  853.0  325300.0
21    0.0  0.0  1.0  0.0  3.0  1.0  280.0  139400.0
22    0.0  0.0  2.0  0.0  3.0  1.0  534.0  230000.0
23    1.0  0.0  1.0  0.0  3.0  1.0  572.0  129900.0
24    1.0  0.0  1.0  0.0  3.0  1.0  270.0  154000.0
25    0.0  0.0  2.0  0.0  3.0  1.0  890.0  256300.0
26    0.0  1.0  1.0  0.0  3.0  0.0  576.0  134800.0
27    1.0  0.0  2.0  0.0  3.0  1.0  772.0  306000.0
28    1.0  0.0  1.0  0.0  2.0  2.0  319.0  207500.0
29    0.0  0.0  1.0  0.0  1.0  0.0  240.0   68500.0
...   ...  ...  ...  ...  ...  ...    ...       ...
1430  0.0  0.0  2.0  1.0  4.0  1.0  372.0  192140.0
1431  0.0  0.0  2.0  0.0  2.0  0.0  440.0  143750.0
1432  0.0  0.0  2.0  0.0  4.0  0.0  216.0   64500.0
1433  1.0  0.0  2.0  1.0  3.0  1.0  451.0  186500.0
1434  1.0  0.0  2.0  0.0  3.0  1.0  484.0  160000.0
1435  1.0  0.0  1.0  1.0  3.0  1.0  462.0  174000.0
1436  0.0  0.0  1.0  0.0  3.0  0.0  528.0  120500.0
1437  1.0  0.0  2.0  0.0  2.0  1.0  774.0  394617.0
1438  1.0  0.0  1.0  0.0  2.0  0.0  923.0  149700.0
1439  0.0  0.0  2.0  1.0  3.0  1.0  550.0  197000.0
1440  0.0  0.0  2.0  0.0  3.0  1.0  672.0  191000.0
1441  1.0  0.0  1.0  0.0  1.0  1.0  420.0  149300.0
1442  1.0  0.0  2.0  1.0  3.0  1.0  812.0  310000.0
1443  0.0  0.0  1.0  0.0  2.0  1.0  192.0  121000.0
1444  0.0  0.0  2.0  0.0  3.0  0.0  626.0  179600.0
1445  1.0  0.0  1.0  0.0  3.0  0.0  240.0  129000.0
1446  0.0  0.0  1.0  0.0  3.0  0.0  312.0  157900.0
1447  1.0  0.0  2.0  1.0  3.0  1.0  556.0  240000.0
1448  0.0  0.0  1.0  1.0  2.0  0.0  384.0  112000.0
1449  1.0  0.0  1.0  0.0  1.0  0.0    0.0   92000.0
1450  0.0  0.0  2.0  2.0  4.0  0.0    0.0  136000.0
1451  0.0  0.0  2.0  0.0  3.0  1.0  840.0  287090.0
1452  1.0  0.0  1.0  0.0  2.0  0.0  525.0  145000.0
1453  0.0  0.0  1.0  0.0  3.0  0.0    0.0   84500.0
1454  1.0  0.0  2.0  0.0  2.0  0.0  400.0  185000.0
1455  0.0  0.0  2.0  1.0  3.0  1.0  460.0  175000.0
1456  1.0  0.0  2.0  0.0  3.0  2.0  500.0  210000.0
1457  0.0  0.0  2.0  0.0  4.0  2.0  252.0  266500.0
1458  1.0  0.0  1.0  0.0  2.0  0.0  240.0  142125.0
1459  1.0  0.0  1.0  1.0  3.0  0.0  276.0  147500.0

[1460 rows x 62 columns]
(1460, 21)
(1460, 62)

In [19]:
type(df_encoded)

numpy.ndarray

In [20]:
# inport DictVectorizer
from sklearn.feature_extraction import DictVectorizer

# convert df into a dictionary: df_dict
df_dict = df.to_dict('records')

# create the Dictvectorizer object :dv
dv = DictVectorizer(sparse = False)

#apply dv on df:df_encoded
df_encoded = dv.fit_transform(df_dict)

# Print dv on df:df_encoded
print(df_encoded[:5,:])

#print vocabulary
#print(dv.vocabulary)

[[  3.00000000e+00   0.00000000e+00   1.00000000e+00   0.00000000e+00
    0.00000000e+00   2.00000000e+00   5.48000000e+02   1.71000000e+03
    1.00000000e+00   5.00000000e+00   8.45000000e+03   6.50000000e+01
    6.00000000e+01   3.00000000e+00   5.00000000e+00   5.00000000e+00
    7.00000000e+00   2.00000000e+00   0.00000000e+00   2.08500000e+05
    2.00300000e+03]
 [  3.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00
    1.00000000e+00   2.00000000e+00   4.60000000e+02   1.26200000e+03
    0.00000000e+00   2.00000000e+00   9.60000000e+03   8.00000000e+01
    2.00000000e+01   3.00000000e+00   2.40000000e+01   8.00000000e+00
    6.00000000e+00   2.00000000e+00   0.00000000e+00   1.81500000e+05
    1.97600000e+03]
 [  3.00000000e+00   0.00000000e+00   1.00000000e+00   0.00000000e+00
    1.00000000e+00   2.00000000e+00   6.08000000e+02   1.78600000e+03
    1.00000000e+00   5.00000000e+00   1.12500000e+04   6.80000000e+01
    6.00000000e+01   3.00000000e+00   5.00000000e+00   5.00000000e+00
    7.00000000e+00   2.00000000e+00   1.00000000e+00   2.23500000e+05
    2.00100000e+03]
 [  3.00000000e+00   0.00000000e+00   1.00000000e+00   0.00000000e+00
    1.00000000e+00   1.00000000e+00   6.42000000e+02   1.71700000e+03
    0.00000000e+00   5.00000000e+00   9.55000000e+03   6.00000000e+01
    7.00000000e+01   3.00000000e+00   6.00000000e+00   5.00000000e+00
    7.00000000e+00   2.00000000e+00   1.00000000e+00   1.40000000e+05
    1.91500000e+03]
 [  4.00000000e+00   0.00000000e+00   1.00000000e+00   0.00000000e+00
    1.00000000e+00   2.00000000e+00   8.36000000e+02   2.19800000e+03
    1.00000000e+00   5.00000000e+00   1.42600000e+04   8.40000000e+01
    6.00000000e+01   3.00000000e+00   1.50000000e+01   5.00000000e+00
    8.00000000e+00   2.00000000e+00   0.00000000e+00   2.50000000e+05
    2.00000000e+03]]

# Implementing Pipelines

In [21]:
df.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Neighborhood,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,...,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,Fireplaces,GarageArea,PavedDrive,SalePrice
0,60,3,65.0,8450,5,0,5,7,5,2003,...,1710,1,0,2,1,3,0,548,2,208500
1,20,3,80.0,9600,24,0,2,6,8,1976,...,1262,0,1,2,0,3,1,460,2,181500
2,60,3,68.0,11250,5,0,5,7,5,2001,...,1786,1,0,2,1,3,1,608,2,223500
3,70,3,60.0,9550,6,0,5,7,5,1915,...,1717,1,0,1,0,3,1,642,2,140000
4,60,3,84.0,14260,15,0,5,8,5,2000,...,2198,1,0,2,1,4,1,836,2,250000

In [22]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression

df=pd.read_csv(r'C:\Users\AMIT\Desktop\MSIT_ML_CLASS-master-6\MSIT_ML_CLASS-master\datasets\ames_unprocessed_data.csv')

In [23]:
df.LotFrontage.fillna(0,inplace=True)

le = LabelEncoder()

#print(df.head())
final_data= df.drop('SalePrice',axis=1)

#create a boolean mask for categorical columns
categorical_mask = (final_data.dtypes=='object')

# Get list of categorical column names
categorical_columns = final_data.columns[categorical_mask].tolist()

final_data[categorical_columns] = final_data[categorical_columns].apply(lambda x: le.fit_transform(x))

final_label = df['SalePrice']

steps=[('ohe',OneHotEncoder(sparse=False, categorical_features=categorical_mask)),
      ('clf',LinearRegression())]

pipeline= Pipeline(steps)

#pipeline.fit(final_data,final_label)   NOT REQUIRED

from sklearn.model_selection import cross_val_score

scores= cross_val_score(pipeline,final_data,final_label,cv=5)

print('Acurracy',scores.mean())

Acurracy 0.829474225486

# GridSearchCV

In [24]:
import xgboost as xgb
max_depth = [2,3,4,5,6,7,8,9,10]

params={'objective':'reg:linear'}

best_rmse =[]
datamatrix=xgb.DMatrix(data=final_data,label=final_label)

for depth in max_depth:
    clf = xgb.XGBRegressor()
    params['max_depth']=depth
    cv_results = xgb.cv(dtrain=datamatrix,params=params,folds=4,num_boost_round=10,metrics='rmse',seed=123,as_pandas=True)
    print(cv_results)
    best_rmse.append(cv_results['test-rmse-mean'].tail().values[-1])
    
print(pd.DataFrame(list(zip(max_depth,best_rmse)),columns=['max_depth','best_rmse']))

TypeError: 'int' object is not iterable

In [25]:
import xgboost as xgb
n_estimator = [10,20,30,40,50]

params ={
    'objective':'reg:linear',
    'max_depth':5
}
best_rmse=[]

datamatrix= xgb.DMatrix(data=final_data,label=final_label)

for depth in n_estimator:
    clf=xgb.XGBRegressor()
    params['n_estimators'] = depth
    cv_results = xgb.cv(dtrain = datamatrix,params=params,folds=4,num_boost_round =10,metrics='rmse',seed=123,as_pandas=True)
    print(cv_results)
    best_rmse.append(cv_results['test-rmse-mean'].tail().values[-1])
#clf.fit(final_data,final_label)

print(pd.DataFrame(list(zip(n_estimator,best_rmse)),columns=['n_estimators','best_rmse']))

plt.plot(n_estimator,best_rmse)

TypeError: 'int' object is not iterable

In [26]:
import xgboost as xgb
max_depth = [2,3,4,5,6,7,8,9,10]

params = {
    "objective" : "reg:linear",
}


best_rmse = []
    
datamatrix = xgb.DMatrix(data=final_data, label=final_label)



for depth in max_depth:
    clf = xgb.XGBRegressor()
    params["max_depth"] = depth
    cv_results = xgb.cv( dtrain=datamatrix, params = params, folds=4, num_boost_round = 10, metrics="rmse", seed=123, as_pandas=True)
    print(cv_results)
    best_rmse.append(cv_results["test-rmse-mean"].tail().values[-1])
    
#     clf.fit(final_data, final_label)

print(pd.DataFrame(list(zip(max_depth, best_rmse)), columns=["max_depth","best_rmse"]))

TypeError: 'int' object is not iterable

In [27]:
import xgboost as xgb

from sklearn.model_selection import GridSearchCV

steps2 = [
    
    ('ohe', OneHotEncoder(categorical_features = categorical_mask)),
    ('clf', xgb.XGBRegressor()) 
]

clf_param_grid = {
    'clf__max_depth' : [2,3,4,5,6,7,8,9,10],
    'clf__learning_rate' : [0.1,0.01]
}

# clf_param_grid = {
#     'clf__max_depth' : [2,3,4,5],
#     'clf__learning_rate' : [0.1,0.01],
#     'clf__n_estimators' : [20,30]
# }

xgbclf = Pipeline(steps2)

estimator = GridSearchCV(xgbclf, param_grid=clf_param_grid ,cv =4, verbose=1, scoring="neg_mean_squared_error")
estimator.fit(final_data,final_label)

print(estimator.best_params_)
import numpy as np 
print(np.sqrt(-1*estimator.best_score_))

Fitting 4 folds for each of 18 candidates, totalling 72 fits

[Parallel(n_jobs=1)]: Done  72 out of  72 | elapsed:   56.8s finished

{'clf__learning_rate': 0.1, 'clf__max_depth': 8}
28405.4003054

In [28]:
import xgboost as xgb
from sklearn.model_selesction import GridSearchCV


steps2=[('ohe',OneHotEncoder(categorical_features = categorical_mask),
        ('clf',xgb.XGBRegressor())]

clf_params_grid ={
    'clf__max_depth':[2,3,4,5,6,7,8,9,10],
    'clf__learning_rate':[0.1,0.01]
}

             
xgbclf = Pipeline(steps2)
             
estimator=GridSearchCV(xgbclf,params_grid=clf_params_grid,cv=4,verbose=1,scoring='neg_mean_squared_error')
estimator.fit(final_data,final_label)

print(estimator.best_params_)
import numpy as np
print(np.sqrt(-1*estimator.best_score_))

SyntaxError: invalid syntax (<ipython-input-28-7a9911f2a062>, line 5)

# Kidney disease dataset

In [29]:
# import necessary modules
import pandas as pd
from sklearn_pandas import DataFrameMapper
from sklearn_pandas import CategoricalImputer
from sklearn.preprocessing import Imputer

data = pd.read_csv(r'C:\Users\AMIT\Desktop\MSIT_ML_CLASS-master-6\MSIT_ML_CLASS-master\datasets\chronic_kidney_with_class.csv')
X=data.iloc[:,:-1]
y=data.iloc[:,-1]

#check number of nulls in each feature column
number_per_column = X.isnull().sum()
print(nulls_per_column)

#Create a boolean mask for categorical columns
categorical_feature_mask = X.dtypes == object

# Get list of categorical column names
categorical_columns=X.columns[categorical_feature_mask].tolist()

# Get list of non-categorical column names
non_categorical_columns = X.columns[~categorical_feature_mask].tolist()

# Apply numeric imputer 
numeric_imputer_mapper = DataFrameMapper([([numeric_feature],Imputer(strategy='median')) for numeric_feature in non_categorical_columns],input_df=True,df_out=True)

# Apply categorical imputer 
categorical_imputer_mapper = DataFrameMapper([(categorical_feature,CategoricalImputer()) for category_feature in non_categorical_columns],input_df=True,df_out=True)

ModuleNotFoundError: No module named 'sklearn_pandas'

In [30]:
data.head()

      RM  LSTAT  PTRATIO      MEDV
0  6.575   4.98     15.3  504000.0
1  6.421   9.14     17.8  453600.0
2  7.185   4.03     17.8  728700.0
3  6.998   2.94     18.7  701400.0
4  7.147   5.33     18.7  760200.0

In [31]:
categorical_feature_mask

NameError: name 'categorical_feature_mask' is not defined

In [32]:
column=data.dtypes == float
columns=data.columns[column].tolist()
columns

['RM', 'LSTAT', 'PTRATIO', 'MEDV']

In [37]:
# Let's play again
from sklearn import svm
clf=svm.SVC(kernel='linear',gamma=1,random_state=24)
clf.fit(X_train,y_train)
preds= clf.predict(X_test)

clf.score(X_test,y_test)

0.030612244897959183